name: deploy

on:
    workflow_dispatch:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
            - name: Adding Known Hosts
              run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Install NPM dependencies
              run: npm install
            - name: Build application
              run: npm run build
            - name: Export application
              run: npm run export
            - name: Deploy with rsync
              run: rsync -avz --no-perms --omit-dir-times --delete ./out/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.HOST_DEPLOY_PATH }} --exclude downloads --exclude keep --exclude ExE1Dlex4PyE78q9BXFv --exclude ExE1Dlex4PyE78q9BXkl --exclude sparcity --exclude toadstool2.0
